dexima_test_task/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("lead_gen.urls", namespace="lead_gen")),
    path("accounts/", include("user.urls", namespace="users")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lead_gen/urls.py
from django.urls import path

from lead_gen.views import LeadGeneratorView

urlpatterns = [
    path("lead_generator/", LeadGeneratorView.as_view(), name="lead_generator"),
]


app_name = "lead_gen"

user/urls.py
from django.urls import path
from .views import UserRegistrationView

urlpatterns = [
    path("register/", UserRegistrationView.as_view(), name="register"),
]

app_name = "users"

lead_gen/models.py
from django.db import models

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.username

lead_gen/forms.py
from django import forms


class LeadGeneratorForm(forms.Form):
    keywords = forms.CharField(label="Keywords")
    location = forms.CharField(label="Location")
    lead_count = forms.IntegerField(
        label="Number of Leads", widget=forms.NumberInput(attrs={"min": 1})
    )

user/forms.py
from django.contrib.auth import get_user_model
from django import forms
from django.contrib.auth.forms import UserCreationForm


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = get_user_model()
        fields = ("username", "email")

lead_gen/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

from .forms import LeadGeneratorForm


class LeadGeneratorView(LoginRequiredMixin, TemplateView):
    template_name = "lead_gen/lead_gen.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = LeadGeneratorForm()
        return context

    def post(self, request, *args, **kwargs):
        form = LeadGeneratorForm(request.POST)
        if form.is_valid():
            keywords = form.cleaned_data["keywords"]
            location = form.cleaned_data["location"]
            lead_count = form.cleaned_data["lead_count"]

            # Implementation of the lead generator, with data from the form

user/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import UserRegistrationForm
from .models import User


class UserRegistrationView(CreateView):
    model = User
    template_name = "registration/register.html"
    form_class = UserRegistrationForm
    success_url = reverse_lazy("login")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Lead Generator</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% include 'includes/navbar.html' %}

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    {% include 'includes/footer.html' %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/includes/footer.html
<footer class="bg-light p-3 text-center">
    <p>&copy; 2023 Dexima Test Task. All rights reserved.</p>
</footer>

templates/includes/navbar.html
<nav class="navbar navbar-expand navbar-dark bg-dark">
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'lead_gen:lead_generator' %}">Lead Generator</a>
    </li>
  </ul>
  <ul class="navbar-nav ml-auto">
    {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link">{{ user.username }}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      </li>
    {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:register' %}">Sign Up</a>
      </li>
    {% endif %}
  </ul>
</nav>

templates/lead_gen/lead_gen.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="card col-md-6 mx-auto">
    <div class="card-body text-center">
      <h2 class="card-title">Lead Generator</h2>
      <form method="post">
        {% csrf_token %}
        {% crispy form %}
        <button type="submit" class="btn btn-primary">Generate Leads</button>
      </form>
    </div>
  </div>
{% endblock %}